In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("academic.csv")

In [3]:
df.head

<bound method NDFrame.head of     gender NationalITy PlaceofBirth       StageID GradeID SectionID  \
0        M          KW       KuwaIT    lowerlevel    G-04         A
1        M          KW       KuwaIT    lowerlevel    G-04         A
2        M          KW       KuwaIT    lowerlevel    G-04         A
3        M          KW       KuwaIT    lowerlevel    G-04         A
4        M          KW       KuwaIT    lowerlevel    G-04         A
..     ...         ...          ...           ...     ...       ...
475      F      Jordan       Jordan  MiddleSchool    G-08         A
476      F      Jordan       Jordan  MiddleSchool    G-08         A
477      F      Jordan       Jordan  MiddleSchool    G-08         A
478      F      Jordan       Jordan  MiddleSchool    G-08         A
479      F      Jordan       Jordan  MiddleSchool    G-08         A

         Topic Semester Relation  raisedhands  VisITedResources  \
0           IT        F   Father         15.0                16
1           IT        F   Father          NaN                20
2           IT        F   Father         10.0                 7
3           IT        F   Father         30.0                25
4           IT        F   Father          0.0                50
..         ...      ...      ...          ...               ...
475  Chemistry        S   Father          5.0                 4
476    Geology        F   Father         50.0                77
477    Geology        S   Father         55.0                74
478    History        F   Father         30.0                17
479    History        S   Father         35.0                14

     AnnouncementsView  Discussion ParentAnsweringSurvey  \
0                    2          20                   Yes
1                    3          25                   Yes
2                    0          30                    No
3                    5          35                    No
4                   12          50                    No
..                 ...         ...                   ...
475                  5           8                    No
476                 14          28                    No
477                 25          29                    No
478                 14          57                    No
479                 23          62                    No

    ParentschoolSatisfaction StudentAbsenceDays Class
0                       Good            Under-7     M
1                       Good            Under-7     M
2                        Bad            Above-7     L
3                        Bad            Above-7     L
4                        Bad            Above-7     M
..                       ...                ...   ...
475                      Bad            Above-7     L
476                      Bad            Under-7     M
477                      Bad            Under-7     M
478                      Bad            Above-7     L
479                      Bad            Above-7     L

[480 rows x 17 columns]>

In [4]:
df.head(n=5)

,gender,NationalITy,PlaceofBirth,StageID,GradeID,SectionID,Topic,Semester,Relation,raisedhands,VisITedResources,AnnouncementsView,Discussion,ParentAnsweringSurvey,ParentschoolSatisfaction,StudentAbsenceDays,Class
0,M,KW,KuwaIT,lowerlevel,G-04,A,IT,F,Father,15.0,16,2,20,Yes,Good,Under-7,M
1,M,KW,KuwaIT,lowerlevel,G-04,A,IT,F,Father,NaN,20,3,25,Yes,Good,Under-7,M
2,M,KW,KuwaIT,lowerlevel,G-04,A,IT,F,Father,10.0,7,0,30,No,Bad,Above-7,L
3,M,KW,KuwaIT,lowerlevel,G-04,A,IT,F,Father,30.0,25,5,35,No,Bad,Above-7,L
4,M,KW,KuwaIT,lowerlevel,G-04,A,IT,F,Father,0.0,50,12,50,No,Bad,Above-7,M

In [5]:
df.tail(n=5)

,gender,NationalITy,PlaceofBirth,StageID,GradeID,SectionID,Topic,Semester,Relation,raisedhands,VisITedResources,AnnouncementsView,Discussion,ParentAnsweringSurvey,ParentschoolSatisfaction,StudentAbsenceDays,Class
475,F,Jordan,Jordan,MiddleSchool,G-08,A,Chemistry,S,Father,5.0,4,5,8,No,Bad,Above-7,L
476,F,Jordan,Jordan,MiddleSchool,G-08,A,Geology,F,Father,50.0,77,14,28,No,Bad,Under-7,M
477,F,Jordan,Jordan,MiddleSchool,G-08,A,Geology,S,Father,55.0,74,25,29,No,Bad,Under-7,M
478,F,Jordan,Jordan,MiddleSchool,G-08,A,History,F,Father,30.0,17,14,57,No,Bad,Above-7,L
479,F,Jordan,Jordan,MiddleSchool,G-08,A,History,S,Father,35.0,14,23,62,No,Bad,Above-7,L

In [13]:
df.index

RangeIndex(start=0, stop=480, step=1)

In [14]:
df.columns

Index(['gender', 'NationalITy', 'PlaceofBirth', 'StageID', 'GradeID',
       'SectionID', 'Topic', 'Semester', 'Relation', 'raisedhands',
       'VisITedResources', 'AnnouncementsView', 'Discussion',
       'ParentAnsweringSurvey', 'ParentschoolSatisfaction',
       'StudentAbsenceDays', 'Class'],
      dtype='object')

In [15]:
df.shape

(480, 17)

In [16]:
df.dtypes

gender                       object
NationalITy                  object
PlaceofBirth                 object
StageID                      object
GradeID                      object
SectionID                    object
Topic                        object
Semester                     object
Relation                     object
raisedhands                 float64
VisITedResources              int64
AnnouncementsView             int64
Discussion                    int64
ParentAnsweringSurvey        object
ParentschoolSatisfaction     object
StudentAbsenceDays           object
Class                        object
dtype: object

In [18]:
print('Total Elements in Datasets:',df.size)

Total Elements in Datasets: 8160

In [21]:
print("Any 5 rows:\n",df.sample(5).T)

Any 5 rows:
                                  1             240         322           412  \
gender                             M             M           M             M
NationalITy                       KW            KW      Jordan     Palestine
PlaceofBirth                  KuwaIT        KuwaIT      Jordan        Jordan
StageID                   lowerlevel  MiddleSchool  lowerlevel  MiddleSchool
GradeID                         G-04          G-07        G-02          G-07
SectionID                          A             B           A             B
Topic                             IT       Science      French       Biology
Semester                           F             S           F             F
Relation                      Father           Mum      Father        Father
raisedhands                      NaN          72.0        10.0          78.0
VisITedResources                  20            80          15            80
AnnouncementsView                  3            98          10            66
Discussion                        25            96          21            51
ParentAnsweringSurvey            Yes           Yes          No           Yes
ParentschoolSatisfaction        Good           Bad         Bad          Good
StudentAbsenceDays           Under-7       Under-7     Above-7       Under-7
Class                              M             H           L             M

                                   395
gender                               M
NationalITy                     Jordan
PlaceofBirth                 Palestine
StageID                   MiddleSchool
GradeID                           G-07
SectionID                            A
Topic                          Biology
Semester                             S
Relation                           Mum
raisedhands                       70.0
VisITedResources                    98
AnnouncementsView                   54
Discussion                          72
ParentAnsweringSurvey              Yes
ParentschoolSatisfaction          Good
StudentAbsenceDays             Under-7
Class                                H

In [23]:
print('Statistical information of Numerical Columns:\n',df.describe().T)

Statistical information of Numerical Columns:
                    count       mean        std  min   25%   50%   75%    max
raisedhands        478.0  46.939331  31.375699  0.0  15.0  50.0  75.0  170.0
VisITedResources   480.0  54.797917  33.080007  0.0  20.0  65.0  84.0   99.0
AnnouncementsView  480.0  37.918750  26.611244  0.0  14.0  33.0  58.0   98.0
Discussion         480.0  43.283333  27.637735  1.0  20.0  39.0  70.0   99.0

In [31]:
print('Total Number of Null Values in Dataset:\n', df.isna().T)

Total Number of Null Values in Dataset:
                             0      1      2      3      4      5      6    \
gender                    False  False  False  False  False  False  False
NationalITy               False  False  False  False  False  False  False
PlaceofBirth              False  False  False  False  False  False  False
StageID                   False  False  False  False  False  False  False
GradeID                   False  False  False  False  False  False  False
SectionID                 False  False  False  False  False  False  False
Topic                     False  False  False  False  False  False  False
Semester                  False  False  False  False  False  False  False
Relation                  False  False  False  False  False  False  False
raisedhands               False   True  False  False  False  False  False
VisITedResources          False  False  False  False  False  False  False
AnnouncementsView         False  False  False  False  False  False  False
Discussion                False  False  False  False  False  False  False
ParentAnsweringSurvey     False  False  False  False  False  False  False
ParentschoolSatisfaction  False  False  False  False  False  False  False
StudentAbsenceDays        False  False  False  False  False  False  False
Class                     False  False  False  False  False  False  False

                            7      8      9    ...    470    471    472  \
gender                    False  False  False  ...  False  False  False
NationalITy               False  False  False  ...  False  False  False
PlaceofBirth              False  False  False  ...  False  False  False
StageID                   False  False  False  ...  False  False  False
GradeID                   False  False  False  ...  False  False  False
SectionID                 False  False  False  ...  False  False  False
Topic                     False  False  False  ...  False  False  False
Semester                  False  False  False  ...  False  False  False
Relation                  False  False  False  ...  False  False  False
raisedhands                True  False  False  ...  False  False  False
VisITedResources          False  False  False  ...  False  False  False
AnnouncementsView         False  False  False  ...  False  False  False
Discussion                False  False  False  ...  False  False  False
ParentAnsweringSurvey     False  False  False  ...  False  False  False
ParentschoolSatisfaction  False  False  False  ...  False  False  False
StudentAbsenceDays        False  False  False  ...  False  False  False
Class                     False  False  False  ...  False  False  False

                            473    474    475    476    477    478    479
gender                    False  False  False  False  False  False  False
NationalITy               False  False  False  False  False  False  False
PlaceofBirth              False  False  False  False  False  False  False
StageID                   False  False  False  False  False  False  False
GradeID                   False  False  False  False  False  False  False
SectionID                 False  False  False  False  False  False  False
Topic                     False  False  False  False  False  False  False
Semester                  False  False  False  False  False  False  False
Relation                  False  False  False  False  False  False  False
raisedhands               False  False  False  False  False  False  False
VisITedResources          False  False  False  False  False  False  False
AnnouncementsView         False  False  False  False  False  False  False
Discussion                False  False  False  False  False  False  False
ParentAnsweringSurvey     False  False  False  False  False  False  False
ParentschoolSatisfaction  False  False  False  False  False  False  False
StudentAbsenceDays        False  False  False  False  False  False  False
Class                     False  False  False  False  False  False  False

[17 rows x 480 columns]

In [32]:
print('Total Number of Null Values in Dataset:\n', df.isna().sum().T)

Total Number of Null Values in Dataset:
 gender                      2
NationalITy                 0
PlaceofBirth                0
StageID                     0
GradeID                     0
SectionID                   0
Topic                       0
Semester                    0
Relation                    0
raisedhands                 2
VisITedResources            0
AnnouncementsView           0
Discussion                  0
ParentAnsweringSurvey       0
ParentschoolSatisfaction    0
StudentAbsenceDays          0
Class                       0
dtype: int64

In [40]:
df['gender'].replace(['M','F'],[0,1],inplace=True)

In [43]:

# Ordinal encoder using Scikit-learn
from sklearn.preprocessing import OrdinalEncoder
enc = OrdinalEncoder()
df[['raisedhands']]=enc.fit_transform(df[['raisedhands']])

In [45]:
print('After converting categorical variable to numeric variable:\n')
print(df.head().T)

After converting categorical variable to numeric variable:

                                   0           1           2           3  \
gender                           0.0         0.0         0.0         0.0
NationalITy                       KW          KW          KW          KW
PlaceofBirth                  KuwaIT      KuwaIT      KuwaIT      KuwaIT
StageID                   lowerlevel  lowerlevel  lowerlevel  lowerlevel
GradeID                         G-04        G-04        G-04        G-04
SectionID                          A           A           A           A
Topic                             IT          IT          IT          IT
Semester                           F           F           F           F
Relation                      Father      Father      Father      Father
raisedhands                     15.0         NaN        10.0        29.0
VisITedResources                  16          20           7          25
AnnouncementsView                  2           3           0           5
Discussion                        20          25          30          35
ParentAnsweringSurvey            Yes         Yes          No          No
ParentschoolSatisfaction        Good        Good         Bad         Bad
StudentAbsenceDays           Under-7     Under-7     Above-7     Above-7
Class                              M           M           L           L

                                   4
gender                           0.0
NationalITy                       KW
PlaceofBirth                  KuwaIT
StageID                   lowerlevel
GradeID                         G-04
SectionID                          A
Topic                             IT
Semester                           F
Relation                      Father
raisedhands                      0.0
VisITedResources                  50
AnnouncementsView                 12
Discussion                        50
ParentAnsweringSurvey             No
ParentschoolSatisfaction         Bad
StudentAbsenceDays           Above-7
Class                              M

In [46]:

df['raisedhands']=(df['raisedhands']-df['raisedhands'].min())/(df['raisedhands'].max()-df['raisedhands'].min())
# (x - min value into that column)/(max value - min value)

In [47]:
df['raisedhands'].min()

0.0

In [48]:
df['raisedhands'].max()

1.0

In [49]:
from sklearn.preprocessing import MaxAbsScaler
abs_scaler=MaxAbsScaler()
df[['VisITedResources ']]=abs_scaler.fit_transform(df[['VisITedResources']])

In [50]:
print(df.head().T)

                                   0           1           2           3  \
gender                           0.0         0.0         0.0         0.0
NationalITy                       KW          KW          KW          KW
PlaceofBirth                  KuwaIT      KuwaIT      KuwaIT      KuwaIT
StageID                   lowerlevel  lowerlevel  lowerlevel  lowerlevel
GradeID                         G-04        G-04        G-04        G-04
SectionID                          A           A           A           A
Topic                             IT          IT          IT          IT
Semester                           F           F           F           F
Relation                      Father      Father      Father      Father
raisedhands                 0.182927         NaN    0.121951    0.353659
VisITedResources                  16          20           7          25
AnnouncementsView                  2           3           0           5
Discussion                        20          25          30          35
ParentAnsweringSurvey            Yes         Yes          No          No
ParentschoolSatisfaction        Good        Good         Bad         Bad
StudentAbsenceDays           Under-7     Under-7     Above-7     Above-7
Class                              M           M           L           L
VisITedResources            0.161616     0.20202    0.070707    0.252525

                                   4
gender                           0.0
NationalITy                       KW
PlaceofBirth                  KuwaIT
StageID                   lowerlevel
GradeID                         G-04
SectionID                          A
Topic                             IT
Semester                           F
Relation                      Father
raisedhands                      0.0
VisITedResources                  50
AnnouncementsView                 12
Discussion                        50
ParentAnsweringSurvey             No
ParentschoolSatisfaction         Bad
StudentAbsenceDays           Above-7
Class                              M
VisITedResources            0.505051

In [51]:
print(df.T)

                                 0           1           2           3    \
gender                           0.0         0.0         0.0         0.0
NationalITy                       KW          KW          KW          KW
PlaceofBirth                  KuwaIT      KuwaIT      KuwaIT      KuwaIT
StageID                   lowerlevel  lowerlevel  lowerlevel  lowerlevel
GradeID                         G-04        G-04        G-04        G-04
SectionID                          A           A           A           A
Topic                             IT          IT          IT          IT
Semester                           F           F           F           F
Relation                      Father      Father      Father      Father
raisedhands                 0.182927         NaN    0.121951    0.353659
VisITedResources                  16          20           7          25
AnnouncementsView                  2           3           0           5
Discussion                        20          25          30          35
ParentAnsweringSurvey            Yes         Yes          No          No
ParentschoolSatisfaction        Good        Good         Bad         Bad
StudentAbsenceDays           Under-7     Under-7     Above-7     Above-7
Class                              M           M           L           L
VisITedResources            0.161616     0.20202    0.070707    0.252525

                                 4           5             6             7    \
gender                           0.0         1.0           0.0           0.0
NationalITy                       KW          KW            KW            KW
PlaceofBirth                  KuwaIT      KuwaIT        KuwaIT        KuwaIT
StageID                   lowerlevel  lowerlevel  MiddleSchool  MiddleSchool
GradeID                         G-04        G-04          G-07          G-07
SectionID                          A           A             A             A
Topic                             IT          IT          Math          Math
Semester                           F           F             F             F
Relation                      Father      Father        Father        Father
raisedhands                      0.0     0.45122      0.390244           NaN
VisITedResources                  50          30            12            10
AnnouncementsView                 12          13             0            15
Discussion                        50          70            17            22
ParentAnsweringSurvey             No         Yes            No           Yes
ParentschoolSatisfaction         Bad         Bad           Bad          Good
StudentAbsenceDays           Above-7     Above-7       Above-7       Under-7
Class                              M           M             L             M
VisITedResources            0.505051     0.30303      0.121212       0.10101

                                   8             9    ...           470  \
gender                             1.0           1.0  ...           0.0
NationalITy                         KW            KW  ...     Palestine
PlaceofBirth                    KuwaIT        KuwaIT  ...        Jordan
StageID                   MiddleSchool  MiddleSchool  ...  MiddleSchool
GradeID                           G-07          G-07  ...          G-08
SectionID                            A             B  ...             A
Topic                             Math            IT  ...       History
Semester                             F             F  ...             F
Relation                        Father        Father  ...        Father
raisedhands                   0.146341      0.658537  ...      0.792683
VisITedResources                    21            80  ...            86
AnnouncementsView                   16            25  ...            86
Discussion                          50            70  ...            41
ParentAnsweringSurvey              Yes           Yes  ...           Yes
ParentschoolSatisfaction          Good          Good  ...          Good
StudentAbsenceDays             Under-7       Under-7  ...       Under-7
Class                                M             M  ...             M
VisITedResources              0.212121      0.808081  ...      0.868687

                                   471           472           473  \
gender                             0.0           0.0           0.0
NationalITy                  Palestine     Palestine     Palestine
PlaceofBirth                    Jordan     Palestine     Palestine
StageID                   MiddleSchool  MiddleSchool  MiddleSchool
GradeID                           G-08          G-08          G-08
SectionID                            A             A             A
Topic                          History       Geology       Geology
Semester                             S             F             S
Relation                        Father        Father        Father
raisedhands                   0.756098      0.780488      0.841463
VisITedResources                    82            87            88
AnnouncementsView                   78            74            79
Discussion                          53            68            70
ParentAnsweringSurvey              Yes           Yes           Yes
ParentschoolSatisfaction          Good          Good          Good
StudentAbsenceDays             Under-7       Under-7       Under-7
Class                                M             M             M
VisITedResources              0.828283      0.878788      0.888889

                                   474           475           476  \
gender                             1.0           1.0           1.0
NationalITy                     Jordan        Jordan        Jordan
PlaceofBirth                    Jordan        Jordan        Jordan
StageID                   MiddleSchool  MiddleSchool  MiddleSchool
GradeID                           G-08          G-08          G-08
SectionID                            A             A             A
Topic                        Chemistry     Chemistry       Geology
Semester                             F             S             F
Relation                        Father        Father        Father
raisedhands                    0.02439      0.060976      0.487805
VisITedResources                     7             4            77
AnnouncementsView                    4             5            14
Discussion                           8             8            28
ParentAnsweringSurvey               No            No            No
ParentschoolSatisfaction           Bad           Bad           Bad
StudentAbsenceDays             Above-7       Above-7       Under-7
Class                                L             L             M
VisITedResources              0.070707      0.040404      0.777778

                                   477           478           479
gender                             1.0           1.0           1.0
NationalITy                     Jordan        Jordan        Jordan
PlaceofBirth                    Jordan        Jordan        Jordan
StageID                   MiddleSchool  MiddleSchool  MiddleSchool
GradeID                           G-08          G-08          G-08
SectionID                            A             A             A
Topic                          Geology       History       History
Semester                             S             F             S
Relation                        Father        Father        Father
raisedhands                   0.536585      0.353659      0.390244
VisITedResources                    74            17            14
AnnouncementsView                   25            14            23
Discussion                          29            57            62
ParentAnsweringSurvey               No            No            No
ParentschoolSatisfaction           Bad           Bad           Bad
StudentAbsenceDays             Under-7       Above-7       Above-7
Class                                M             L             L
VisITedResources              0.747475      0.171717      0.141414

[18 rows x 480 columns]